### ISSUE TITLE
Conv-AE Results not reproducable

### ISSUE THREAD

**Issue by arnelochner** [waico/SKAB#26]
With the notebook provided for the Conv-AE Anomaly-Detector I am not able to reproduce the metrics reported by this repo.

I did not change any code in the notebook.

The models result in the following metrics:

![grafik](https://user-images.githubusercontent.com/57033688/143212610-815b54ef-59a9-4007-a133-5127775d6e98.png)

**Comment by YKatser** [comment]
Hello @arnelochner,

Did you check if the other results (for other methods) are reproducible?
