### ISSUE TITLE
Prepare English version of EDA

### ISSUE THREAD

**Issue by YKatser** [waico/SKAB#28]

**Comment by 17011813** [comment]
Good Morning :)

I wanna know when are you gonna upload **the English version of EDA** on kaggle? 
Also, where can I get **upcoming update to v1.0**? I want to get more anomaly and anomaly-free dataset :)
Can u plz share more valve datasets?

Thanks for your great work!
Have a great day.

**Comment by YKatser** [comment]
The answer to the [comment](https://github.com/waico/SKAB/issues/28#issuecomment-1017168010) by @17011813 is in the separate issue #32.
