### ISSUE TITLE
utils/evaluating.py

### ISSUE THREAD

**Issue by niklasnordin** [waico/SKAB#37]
... has gone missing from the repo

**Comment by abdurrahman1828** [comment]
Could you please update the missing script of evaluating.py?

**Comment by KozitsinSlava** [comment]
> Could you please update the missing script of evaluating.py?
> ... has gone missing from the repo

We've changed the code a bit. The evaluating function is now available from our tsad package, you can find the actual usage of this library here https://github.com/waico/SKAB/blob/master/notebooks/ArimaFD.ipynb.
or use: 
from tsad.evaluating.evaluating import evaluating
