### ISSUE TITLE
Sensor details

### ISSUE THREAD

**Issue by brycheiniog** [waico/SKAB#38]
Thanks for this very interesting project. Could you provide a few more details about the sensors and their location within your test bed? I am particularly interested in the location of the two accelerometers.

Many thanks.

**Comment by 17011813** [comment]
Good Morning :)

I want to know detailed information about anomaly-free data.
Is anomaly-free data is from the valve1 or valve 2 datasets?
Or where are anomaly-free data collected from?

Is there any differences in normal (0) data of all csv file?
For example, I know that the abnormal (1) data in **valve1.csv** and **valve2.csv** are definitely different.
By the way, is the normal (0) data in **valve1.csv** and **valve2.csv** almost the same data?

Thank you so much!

**Comment by YKatser** [comment]
@brycheiniog 
The details regarding the sensors are currently available here: https://drive.google.com/open?id=1dHUevwPp6ftQCEKnRgB4KMp9oLBMSiDM (7th slide)

**Comment by YKatser** [comment]
@17011813 Hello! anomaly-free data is collected from the same testbed, just in different time. It is just a coincidence that normal data in **valve1.csv** and **valve2.csv** almost the same. They are collected separately as well.
