### ISSUE TITLE
About evaluating code

### ISSUE THREAD

**Issue by 17011813** [waico/SKAB#39]
Hello :)

Where can I get **evaluating** python code file in your repository?

https://github.com/waico/SKAB/blob/9b9ad7b2a8daab21d6184fcdf50e3d4a8512e68c/notebooks/autoencoder.ipynb?short_path=e2cd0f3#L24

Thank you.

**Comment by Lux3833** [comment]
You can check out the original branch, there will be evaluating.py file in dir /utils

**Comment by 17011813** [comment]
Thanks for answering my question!
I found it thank you.

Btw I want to read the Position paper (currently submitted for publication) that you wrote about SKAB benchmark dataset.
Where can I get your paper to explore your dataset more in detail?

Thanks Good night!

**Comment by 17011813** [comment]
Thanks for answering my question!
I found the code thank you.
By the way, I wanna read your Skoltech Anomaly Benchmark (SKAB) Position paper (currently submitted for publication) to understand your dataset in detail.
Can you send me a paper or let me know how to access your paper?

Thanks :)

**Comment by YKatser** [comment]
@17011813 
Answered here: https://github.com/waico/SKAB/issues/37
