### ISSUE TITLE
irregular sampling rate and gaps

### ISSUE THREAD

**Issue by eichlerwest** [waico/SKAB#62]
One of the files contains only 104 points before the first anomaly is introduced, which means that it is not possible to train on the first 400 points as suggested. 

All the files are irregularly sampled with some intervals 2 seconds instead of 1 second. Three files contain gaps of greater than 50 seconds. Two more have multiple gaps of 3, 4, and 5 seconds throughout. 

As such, the data is not really usable for a ML study.

**Comment by YKatser** [comment]
Thank you for your feedback! From my experience, real-world data in heavy industry and technical applications is often much worse in terms of data issues. I even have a [post on medium](https://medium.com/@katser/quality-issues-in-industrial-time-series-data-b15d02c28024) about them. Maybe you might like more [SKAB teaser](https://www.kaggle.com/datasets/yuriykatser/skoltech-anomaly-benchmark-skab-teaser/data), where the data is better structured (still not perfect). Preprocessing of SKAB teaser is available [here](https://www.kaggle.com/code/yuriykatser/baseline-ff-autoencoder-for-anomaly-detection).
