### ISSUE TITLE
The idea of using SKAB as a forecasting benchmark. 

### ISSUE THREAD

**Issue by waico** [waico/SKAB#8]
In real technical systems, there are the following tasks of the diagnostic system: early detection of faults (anomalies), finding the root causes, and predicting the development of faults. The last task gives the greatest economic effects since it allows you to determine the time to failure, which makes it possible to optimize MRO. SCAB's capabilities allow it to be used as a predictive benchmark. Now work is underway to bring the idea to life.

**Comment by 17011813** [comment]
Hello, I wanna know how can SKAB dataset could be used in real world applications.
Is this dataset could be used for building anomaly detection?

I want to know more detail informations for writing a paper with this dataset.
Thank you!
